onokatioをAdminにする
ictsc/ictsc-github-member pull request #172
Opened 2022-11-18 17:45 UTC by onokatio

2022-11-18 20:07 UTC, x86taka requested changes

2022-11-18 20:07 UTC, x86taka commented on team-admin.tf
> +  username = "${github_membership.proelbtn.onokatio}"
usernameが誤っていそう

2022-11-19 14:55 UTC, onokatio commented on team-admin.tf
> +  username = "${github_membership.proelbtn.onokatio}"
コピペするときにミスった

2022-11-20 02:20 UTC, x86taka approved these changes

2022-11-20 02:21 UTC, merged